Feat/develop/payment integration
mojitoinc/mojito-mixer-v2 pull request #36
Opened 2023-02-09 14:03 UTC by sakthi-ionixx

ValidPaymentLimit API integration

2023-02-09 14:07 UTC, alexinx commented on app/src/lib/providers/PaymentProvider.tsx
> +export interface ShowPaymentMethods {
```suggestion
export interface PaymentMethodLimit {
```

2023-02-09 14:08 UTC, alexinx commented on app/src/lib/providers/PaymentProvider.tsx
> +  showCreditCard?: boolean;
```suggestion
  exceedCreditCard?: boolean;
```

2023-02-10 05:55 UTC, ShowriSrinivas requested changes

2023-02-10 05:55 UTC, ShowriSrinivas commented on app/src/stories/creditCard.stories.tsx
> +      PaymentMethodLimit={{
Prop name is wrong change it to paymentMethodLimit

2023-02-10 05:55 UTC, ShowriSrinivas commented on app/src/stories/wireTransfer.stories.tsx
> +      PaymentMethodLimit={{
same as above

2023-02-10 06:06 UTC, ShowriSrinivas approved these changes

2023-02-10 06:06 UTC, merged